/**
 * SounnyMap – app.js
 * ==================
 * Core application logic for the GIS mapping platform.
 *
 * SECTIONS
 * ────────
 *  1. Configuration & Basemap Definitions
 *  2. Application State
 *  3. Map Initialisation
 *  4. Basemap Switcher
 *  5. GeoJSON Data Loader
 *  6. Layer Management
 *  7. Feature Click Popups
 *  8. Layout Mode
 *  9. PDF Export
 * 10. Scale Bar (layout overlay)
 * 11. Utilities (colour, toast)
 * 12. Event Listeners
 * 13. Bootstrap
 *
 * EXTENDING FOR EARTH OBSERVATION & AGENT TOOLS
 * ─────────────────────────────────────────────
 * • To add a WMS/WCS raster layer (e.g. from NASA Earthdata or Copernicus):
 *     addRasterLayer(id, wmsUrl, layerName)   ← see stub at the bottom
 * • To add a COG (Cloud-Optimised GeoTIFF) via a tile server:
 *     addRasterLayer(id, 'https://tiles.rdnt.io/tiles/{z}/{x}/{y}@2x?url=<cogUrl>')
 * • To stream real-time GeoJSON from an agent API, call loadGeoJSON(id, geojsonObject)
 *   and update it with updateLayerData(id, newGeojsonObject).
 */

'use strict';

/* ============================================================
   1. CONFIGURATION & BASEMAP DEFINITIONS
   ============================================================
   Add or swap basemap styles here. Each entry must be either:
     • A MapLibre Style Specification URL (string), or
     • An inline MapLibre Style Specification object.

   Free tile services used:
     • Street  – OpenFreeMap Liberty style (no API key required)
                 https://openfreemap.org
     • Satellite – ESRI World Imagery raster tiles (free for web use)
                   https://www.esri.com/en-us/legal/terms/full-master-agreement
   ============================================================ */

/** Default center [longitude, latitude] and zoom for the initial view */
const INITIAL_CENTER = [0, 20];
const INITIAL_ZOOM   = 2;

/**
 * Street basemap: OpenFreeMap Liberty (vector tiles, MapLibre-native)
 * No API key required. Replace this URL to use a different provider,
 * e.g. MapTiler, Stadia Maps, or your own tile server.
 */
const STREET_STYLE = 'https://tiles.openfreemap.org/styles/liberty';

/**
 * Satellite basemap: ESRI World Imagery served as a raster XYZ tile source.
 * Constructed as an inline MapLibre Style Specification so it can be
 * used alongside any vector data layers added by the user.
 */
const SATELLITE_STYLE = {
  version: 8,
  name: 'Satellite',
  sources: {
    // ── Earth Observation hook ──────────────────────────────────────────
    // Replace the 'tiles' URL below with any XYZ raster tile endpoint,
    // e.g. a WMS/TMS wrapper around Sentinel-2, Landsat, or a custom
    // raster tile server generated by a geo-processing agent.
    'esri-satellite': {
      type: 'raster',
      tiles: [
        'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
      ],
      tileSize: 256,
      attribution: 'Tiles &copy; Esri &mdash; Source: Esri, DigitalGlobe, GeoEye, ' +
                   'Earthstar Geographics, CNES/Airbus DS, USDA, USGS, AeroGRID, IGN, and the GIS User Community'
    }
  },
  layers: [
    {
      id: 'esri-satellite-layer',
      type: 'raster',
      source: 'esri-satellite',
      minzoom: 0,
      maxzoom: 19
    }
  ]
};

/* ============================================================
   2. APPLICATION STATE
   ============================================================ */

/** Tracks every user-loaded GeoJSON layer keyed by a unique layer ID */
const layers = {};

/** Current basemap key: 'street' | 'satellite' */
let currentBasemap = 'street';

/** Whether Layout Mode is currently active */
let layoutModeActive = false;

/** Counter used to generate unique layer IDs */
let layerCounter = 0;

/** Palette of distinguishable colours assigned round-robin to new layers */
const LAYER_COLORS = [
  '#3b82f6', // blue
  '#10b981', // emerald
  '#f59e0b', // amber
  '#ef4444', // red
  '#8b5cf6', // violet
  '#06b6d4', // cyan
  '#f97316', // orange
  '#ec4899', // pink
  '#84cc16', // lime
  '#14b8a6'  // teal
];

/* ============================================================
   3. MAP INITIALISATION
   ============================================================ */

/**
 * Initialise the MapLibre GL JS map.
 *
 * preserveDrawingBuffer: true  – required to read the canvas pixel
 *   data for PDF / image export (slight performance cost; safe for GIS use).
 *
 * To change the starting view, edit INITIAL_CENTER and INITIAL_ZOOM above.
 */
const map = new maplibregl.Map({
  container: 'map',         // ID of the <div> that will hold the map
  style: STREET_STYLE,      // Initial basemap style URL
  center: INITIAL_CENTER,
  zoom: INITIAL_ZOOM,
  preserveDrawingBuffer: true   // Needed for canvas → image export
});

/* ── Standard map controls ─────────────────────────────────────────────
   Zoom in / out buttons are placed top-right.
   Scale bar is placed bottom-left.
   To reposition controls, change the 'position' argument.
   See: https://maplibre.org/maplibre-gl-js/docs/API/#icontrol
   ────────────────────────────────────────────────────────────────────── */
map.addControl(new maplibregl.NavigationControl({ showCompass: true }), 'top-right');
map.addControl(new maplibregl.ScaleControl({ maxWidth: 150, unit: 'metric' }), 'bottom-left');

/** Update the header coordinate / zoom display as the user moves the cursor */
map.on('mousemove', (e) => {
  const { lng, lat } = e.lngLat;
  document.getElementById('map-coords').textContent =
    `${lat.toFixed(4)}°, ${lng.toFixed(4)}°`;
});

/** Keep zoom level display in sync */
map.on('zoomend', () => {
  document.getElementById('map-zoom').textContent =
    `Zoom: ${map.getZoom().toFixed(1)}`;
});

/** When the map moves in layout mode, refresh the dynamic scale bar */
map.on('moveend', () => {
  if (layoutModeActive) updateLayoutScale();
});

/* ============================================================
   4. BASEMAP SWITCHER
   ============================================================ */

/**
 * Switch the active basemap and re-add any user layers on top.
 *
 * When the basemap changes, MapLibre reloads the entire style, which
 * removes all sources and layers that were added programmatically.
 * The 'styledata' event fires once the new style is ready; we then
 * restore every layer stored in the `layers` state object.
 *
 * @param {'street'|'satellite'} basemapKey
 */
function switchBasemap(basemapKey) {
  if (basemapKey === currentBasemap) return;

  currentBasemap = basemapKey;
  const newStyle = basemapKey === 'satellite' ? SATELLITE_STYLE : STREET_STYLE;

  // Style is loaded asynchronously; user layers are restored in the handler below
  map.setStyle(newStyle);

  // Update active state on buttons
  document.querySelectorAll('.basemap-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.basemap === basemapKey);
  });
}

/**
 * After a style change, restore all previously loaded user layers.
 * This fires every time `setStyle` completes.
 */
map.on('styledata', () => {
  Object.values(layers).forEach(layerInfo => {
    if (!map.getSource(layerInfo.sourceId)) {
      addLayerToMap(layerInfo);
    }
  });
});

/* ============================================================
   5. GeoJSON DATA LOADER
   ============================================================ */

/**
 * Read one or more GeoJSON files selected via the file input or dropped
 * onto the upload area, validate them, and add them to the map.
 *
 * @param {FileList|File[]} files
 */
function loadFiles(files) {
  Array.from(files).forEach(file => {
    if (!file.name.match(/\.(geojson|json)$/i)) {
      showToast(`Skipped "${file.name}" – not a GeoJSON file.`, 'warning');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const geojson = JSON.parse(e.target.result);
        // Validate minimal GeoJSON structure
        if (!geojson.type) throw new Error('Missing "type" property – not valid GeoJSON.');

        const layerName = file.name.replace(/\.(geojson|json)$/i, '');
        loadGeoJSON(layerName, geojson);
        showToast(`Loaded "${layerName}"`, 'success');
      } catch (err) {
        showToast(`Error in "${file.name}": ${err.message}`, 'error');
        console.error('[SounnyMap] GeoJSON parse error:', err);
      }
    };
    reader.readAsText(file);
  });
}

/**
 * Add a GeoJSON object to the map as a new layer.
 * This is the primary entry-point for programmatically adding data –
 * call it from external scripts or agent integrations.
 *
 * @param {string} name   - Human-readable layer name shown in the sidebar
 * @param {object} geojson - Valid GeoJSON FeatureCollection, Feature, or Geometry
 */
function loadGeoJSON(name, geojson) {
  const id     = `layer-${++layerCounter}`;
  const srcId  = `${id}-source`;
  const color  = LAYER_COLORS[(layerCounter - 1) % LAYER_COLORS.length];

  const layerInfo = {
    id,
    sourceId: srcId,
    name,
    color,
    visible: true,
    geojson
  };

  layers[id] = layerInfo;
  addLayerToMap(layerInfo);
  renderLayerList();
  updateLayerCount();

  // Zoom to the loaded data
  const bounds = computeBounds(geojson);
  if (bounds) {
    map.fitBounds(bounds, { padding: 50, maxZoom: 14, duration: 800 });
  }

  // If layout mode is active, refresh the legend
  if (layoutModeActive) buildLayoutLegend();
}

/**
 * Internal: add the MapLibre source + visual layers for a layerInfo object.
 * Handles Points, Lines, and Polygons automatically.
 *
 * To customise the visual style of loaded data (e.g. colour ramps for
 * Earth Observation products), modify the layer paint properties below.
 *
 * @param {object} layerInfo
 */
function addLayerToMap(layerInfo) {
  const { id, sourceId, geojson, color } = layerInfo;

  // Add the GeoJSON as a MapLibre source
  // ── EO / Agent hook ─────────────────────────────────────────────────
  // To display live data, call map.getSource(sourceId).setData(newGeoJSON)
  // when new data arrives from an API or agent tool.
  // ────────────────────────────────────────────────────────────────────
  map.addSource(sourceId, { type: 'geojson', data: geojson });

  // Polygon fill layer
  map.addLayer({
    id: `${id}-fill`,
    type: 'fill',
    source: sourceId,
    filter: ['==', ['geometry-type'], 'Polygon'],
    paint: {
      'fill-color': color,
      'fill-opacity': 0.35
    }
  });

  // Polygon + LineString outline / stroke layer
  map.addLayer({
    id: `${id}-line`,
    type: 'line',
    source: sourceId,
    filter: ['any',
      ['==', ['geometry-type'], 'LineString'],
      ['==', ['geometry-type'], 'Polygon'],
      ['==', ['geometry-type'], 'MultiLineString'],
      ['==', ['geometry-type'], 'MultiPolygon']
    ],
    paint: {
      'line-color': color,
      'line-width': 2
    }
  });

  // Point / circle layer
  map.addLayer({
    id: `${id}-circle`,
    type: 'circle',
    source: sourceId,
    filter: ['==', ['geometry-type'], 'Point'],
    paint: {
      'circle-color': color,
      'circle-radius': 5,
      'circle-stroke-color': '#fff',
      'circle-stroke-width': 1.5
    }
  });

  // Attach click handlers for feature popups
  [`${id}-fill`, `${id}-line`, `${id}-circle`].forEach(lid => {
    map.on('click', lid, featureClickHandler);
    map.on('mouseenter', lid, () => { map.getCanvas().style.cursor = 'pointer'; });
    map.on('mouseleave', lid, () => { map.getCanvas().style.cursor = ''; });
  });
}

/* ============================================================
   6. LAYER MANAGEMENT
   ============================================================ */

/**
 * Toggle a layer's visibility on / off.
 * @param {string} layerId
 */
function toggleLayerVisibility(layerId) {
  const info = layers[layerId];
  if (!info) return;

  info.visible = !info.visible;
  const visibility = info.visible ? 'visible' : 'none';

  [`${layerId}-fill`, `${layerId}-line`, `${layerId}-circle`].forEach(lid => {
    if (map.getLayer(lid)) {
      map.setLayoutProperty(lid, 'visibility', visibility);
    }
  });

  renderLayerList();
  if (layoutModeActive) buildLayoutLegend();
}

/**
 * Remove a layer and its source from the map and from state.
 * @param {string} layerId
 */
function removeLayer(layerId) {
  const info = layers[layerId];
  if (!info) return;

  [`${layerId}-fill`, `${layerId}-line`, `${layerId}-circle`].forEach(lid => {
    if (map.getLayer(lid)) map.removeLayer(lid);
  });
  if (map.getSource(info.sourceId)) map.removeSource(info.sourceId);

  delete layers[layerId];
  renderLayerList();
  updateLayerCount();
  if (layoutModeActive) buildLayoutLegend();
}

/**
 * Zoom the map to fit a specific layer.
 * @param {string} layerId
 */
function zoomToLayer(layerId) {
  const info = layers[layerId];
  if (!info) return;
  const bounds = computeBounds(info.geojson);
  if (bounds) map.fitBounds(bounds, { padding: 60, duration: 700 });
}

/**
 * Update the live data of an existing layer (e.g. from an agent feed).
 * Useful for real-time EO data updates without removing/re-adding the layer.
 *
 * @param {string} layerId  - the ID returned / tracked in the `layers` state
 * @param {object} newGeoJSON - fresh GeoJSON data
 */
function updateLayerData(layerId, newGeoJSON) {
  const info = layers[layerId];
  if (!info) return;
  info.geojson = newGeoJSON;
  const src = map.getSource(info.sourceId);
  if (src) src.setData(newGeoJSON);
}

/** Re-render the layer list in the sidebar */
function renderLayerList() {
  const container = document.getElementById('layer-list');
  const ids = Object.keys(layers);

  if (ids.length === 0) {
    container.innerHTML = '<p class="empty-hint">No layers loaded.<br>Upload a GeoJSON file to begin.</p>';
    return;
  }

  container.innerHTML = '';
  // Show most-recently added first
  [...ids].reverse().forEach(id => {
    const info = layers[id];
    const item = document.createElement('div');
    item.className = 'layer-item';
    item.dataset.layerId = id;

    item.innerHTML = `
      <span class="layer-color" style="background:${info.color}"></span>
      <span class="layer-name${info.visible ? '' : ' dimmed'}" title="${info.name}">${info.name}</span>
      <div class="layer-actions">
        <button class="layer-btn" data-action="zoom"    title="Zoom to layer">⊕</button>
        <button class="layer-btn" data-action="toggle"  title="${info.visible ? 'Hide' : 'Show'} layer">${info.visible ? '👁' : '🚫'}</button>
        <button class="layer-btn danger" data-action="remove" title="Remove layer">✕</button>
      </div>
    `;

    // Event delegation on the item
    item.addEventListener('click', (e) => {
      const btn = e.target.closest('[data-action]');
      if (!btn) return;
      const action = btn.dataset.action;
      if (action === 'zoom')    zoomToLayer(id);
      if (action === 'toggle')  toggleLayerVisibility(id);
      if (action === 'remove')  removeLayer(id);
    });

    container.appendChild(item);
  });
}

/** Update the layer count badge in the sidebar */
function updateLayerCount() {
  document.getElementById('layer-count').textContent = Object.keys(layers).length;
}

/* ============================================================
   7. FEATURE CLICK POPUPS
   ============================================================ */

/**
 * Show a popup with the clicked feature's properties.
 * @param {maplibregl.MapMouseEvent} e
 */
function featureClickHandler(e) {
  const feature = e.features[0];
  if (!feature) return;

  const props = feature.properties || {};
  const keys  = Object.keys(props);

  let content = '<div class="popup-title">Feature Properties</div>';

  if (keys.length === 0) {
    content += '<p style="color:var(--text-muted);font-size:12px">No properties.</p>';
  } else {
    content += '<table class="popup-table">';
    keys.forEach(k => {
      const val = props[k];
      // Truncate very long values
      const display = (typeof val === 'string' && val.length > 80)
        ? val.slice(0, 80) + '…'
        : val;
      content += `<tr>
        <td class="prop-key">${escapeHtml(String(k))}</td>
        <td class="prop-val">${escapeHtml(String(display ?? ''))}</td>
      </tr>`;
    });
    content += '</table>';
  }

  new maplibregl.Popup({ closeButton: true, maxWidth: '300px' })
    .setLngLat(e.lngLat)
    .setHTML(content)
    .addTo(map);
}

/* ============================================================
   8. LAYOUT MODE
   ============================================================ */

/**
 * Activate Layout Mode:
 *  • Shows the layout overlay elements on the map
 *  • Opens the layout editor panel
 *  • Refreshes dynamic elements (legend, scale)
 */
function activateLayoutMode() {
  layoutModeActive = true;

  document.getElementById('layout-overlay').classList.remove('hidden');
  document.getElementById('layout-panel').classList.remove('hidden');
  document.getElementById('layout-mode-btn').classList.add('active');

  syncLayoutOverlay();
  updateLayoutScale();
  showToast('Layout mode active – configure elements then export.', 'info');
}

/**
 * Deactivate Layout Mode:
 *  • Hides all overlay elements
 *  • Closes the editor panel
 */
function deactivateLayoutMode() {
  layoutModeActive = false;

  document.getElementById('layout-overlay').classList.add('hidden');
  document.getElementById('layout-panel').classList.add('hidden');
  document.getElementById('layout-mode-btn').classList.remove('active');

  // Hide individual elements
  ['lo-title', 'lo-north', 'lo-legend', 'lo-scale', 'lo-sources'].forEach(id => {
    document.getElementById(id).classList.add('hidden');
  });
}

/**
 * Read the current state of all layout checkboxes / inputs and update
 * the overlay elements accordingly.
 */
function syncLayoutOverlay() {
  // Title
  const showTitle = document.getElementById('lp-show-title').checked;
  const titleEl   = document.getElementById('lo-title');
  titleEl.classList.toggle('hidden', !showTitle);
  if (showTitle) {
    document.getElementById('lo-title-text').textContent =
      document.getElementById('lp-title-input').value || 'Map Title';
  }

  // North arrow
  document.getElementById('lo-north')
    .classList.toggle('hidden', !document.getElementById('lp-show-north').checked);

  // Legend
  const showLegend = document.getElementById('lp-show-legend').checked;
  document.getElementById('lo-legend').classList.toggle('hidden', !showLegend);
  if (showLegend) buildLayoutLegend();

  // Scale
  const showScale = document.getElementById('lp-show-scale').checked;
  document.getElementById('lo-scale').classList.toggle('hidden', !showScale);
  if (showScale) updateLayoutScale();

  // Sources
  const showSources  = document.getElementById('lp-show-sources').checked;
  const sourcesEl    = document.getElementById('lo-sources');
  sourcesEl.classList.toggle('hidden', !showSources);
  if (showSources) {
    document.getElementById('lo-sources-text').textContent =
      document.getElementById('lp-sources-input').value || '';
  }
}

/**
 * Populate the legend overlay with entries for every visible layer.
 */
function buildLayoutLegend() {
  const container = document.getElementById('lo-legend-content');
  container.innerHTML = '';

  const visible = Object.values(layers).filter(l => l.visible);
  if (visible.length === 0) {
    container.innerHTML = '<p style="font-size:11px;color:#666">No layers loaded</p>';
    return;
  }

  visible.forEach(info => {
    const item = document.createElement('div');
    item.className = 'lo-legend-item';
    item.innerHTML = `
      <span class="lo-legend-swatch" style="background:${info.color}"></span>
      <span>${escapeHtml(info.name)}</span>
    `;
    container.appendChild(item);
  });
}

/* ============================================================
   9. PDF EXPORT
   ============================================================ */

/**
 * Export the current map view and layout elements as a PDF.
 *
 * Strategy:
 *  1. Capture the map canvas as a PNG data-URL (requires preserveDrawingBuffer).
 *  2. Build an HTML document containing the map image + overlay elements.
 *  3. Open it in a new window and trigger the browser's print dialog.
 *  4. The user selects "Save as PDF" in the print destination.
 *
 * This approach is dependency-free and produces reliable results across
 * all modern browsers without requiring a PDF library.
 */
function exportToPDF() {
  // Snapshot the current map as an image
  const mapCanvas = map.getCanvas();
  const mapDataURL = mapCanvas.toDataURL('image/png');

  // Gather layout element values
  const title      = document.getElementById('lp-title-input').value || '';
  const sources    = document.getElementById('lp-sources-input').value || '';
  const showTitle  = document.getElementById('lp-show-title').checked;
  const showNorth  = document.getElementById('lp-show-north').checked;
  const showLegend = document.getElementById('lp-show-legend').checked;
  const showScale  = document.getElementById('lp-show-scale').checked;
  const showSrc    = document.getElementById('lp-show-sources').checked;

  // Build the legend HTML
  const legendItems = Object.values(layers)
    .filter(l => l.visible)
    .map(l => `<div class="leg-item">
      <span class="leg-swatch" style="background:${l.color}"></span>
      <span>${escapeHtml(l.name)}</span>
    </div>`).join('');

  // North arrow SVG
  const northSVG = `
    <svg viewBox="0 0 40 72" xmlns="http://www.w3.org/2000/svg" width="36" height="65">
      <text x="20" y="11" text-anchor="middle" font-size="11" font-weight="bold" fill="#222" font-family="sans-serif">N</text>
      <polygon points="20,14 28,44 20,38 12,44" fill="white" stroke="#222" stroke-width="1.5"/>
      <polygon points="20,62 28,44 20,38 12,44" fill="#333" stroke="#222" stroke-width="1.5"/>
    </svg>`;

  // Scale bar values (captured from the live scale display)
  const scaleLabel = document.getElementById('lo-scale-label').textContent || '';
  const scaleWidth = document.getElementById('lo-scale-bar').style.width || '100px';

  // Build the print page
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title || 'Map Export')}</title>
  <style>
    @page { size: A4 landscape; margin: 10mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', sans-serif; background: #fff; }
    .print-wrap {
      position: relative;
      width: 100%;
      height: calc(100vh - 0px);
      overflow: hidden;
    }
    .map-img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
    .overlay { position: absolute; }
    /* Title */
    .p-title {
      top: 14px; left: 50%; transform: translateX(-50%);
      background: rgba(255,255,255,0.92);
      padding: 7px 20px;
      font-size: 20px; font-weight: 700;
      border-radius: 5px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.25);
      white-space: nowrap;
    }
    /* North arrow */
    .p-north {
      top: 14px; right: 14px;
      background: rgba(255,255,255,0.92);
      padding: 6px;
      border-radius: 5px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.25);
    }
    /* Legend */
    .p-legend {
      bottom: 50px; left: 14px;
      background: rgba(255,255,255,0.92);
      padding: 10px 12px;
      border-radius: 5px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.25);
      min-width: 120px;
      font-size: 12px;
    }
    .leg-title { font-weight: 700; margin-bottom: 6px; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }
    .leg-item  { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
    .leg-swatch { width: 14px; height: 14px; border-radius: 3px; flex-shrink: 0; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
    /* Scale */
    .p-scale {
      bottom: 50px; left: 50%; transform: translateX(-50%);
      background: rgba(255,255,255,0.92);
      padding: 5px 12px;
      border-radius: 5px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.25);
      display: flex; flex-direction: column; align-items: center; gap: 3px;
    }
    .scale-bar {
      height: 6px;
      border: 2px solid #333;
      border-top: none;
      width: ${scaleWidth};
      print-color-adjust: exact;
      -webkit-print-color-adjust: exact;
    }
    .scale-txt { font-size: 11px; font-weight: 600; color: #222; }
    /* Sources */
    .p-sources {
      bottom: 50px; right: 14px;
      background: rgba(255,255,255,0.92);
      padding: 6px 10px;
      border-radius: 5px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.25);
      max-width: 220px;
      font-size: 11px;
      line-height: 1.5;
    }
  </style>
</head>
<body>
  <div class="print-wrap">
    <img class="map-img" src="${mapDataURL}" alt="Map" />

    ${showTitle  ? `<div class="overlay p-title">${escapeHtml(title)}</div>` : ''}
    ${showNorth  ? `<div class="overlay p-north">${northSVG}</div>` : ''}
    ${showLegend && legendItems ? `
      <div class="overlay p-legend">
        <div class="leg-title">Legend</div>
        ${legendItems}
      </div>` : ''}
    ${showScale && scaleLabel ? `
      <div class="overlay p-scale">
        <div class="scale-bar"></div>
        <div class="scale-txt">${escapeHtml(scaleLabel)}</div>
      </div>` : ''}
    ${showSrc && sources ? `
      <div class="overlay p-sources">
        <strong>Sources:</strong> ${escapeHtml(sources)}
      </div>` : ''}
  </div>
  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    };
  <\/script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    showToast('Popup blocked. Please allow popups for this site.', 'warning');
    return;
  }
  win.document.write(html);
  win.document.close();
}

/* ============================================================
   10. SCALE BAR (layout overlay)
   ============================================================ */

/**
 * Compute the map scale in km for a fixed pixel width (100 px) and
 * update the scale bar element in the layout overlay.
 *
 * Formula: metres per pixel at the current zoom and latitude.
 *   metersPerPx = (earthCircumference * cos(lat)) / (2^zoom * tileSize)
 */
function updateLayoutScale() {
  const SCALE_BAR_PX = 100; // width in pixels to represent on the bar

  const zoom   = map.getZoom();
  const lat    = map.getCenter().lat;
  const metersPerPx =
    (40075016.686 * Math.abs(Math.cos((lat * Math.PI) / 180))) /
    (Math.pow(2, zoom) * 256);

  let totalMetres = metersPerPx * SCALE_BAR_PX;
  let label;

  // Round to a "nice" number for readability
  const nice = niceNumber(totalMetres);
  const niceWidth = Math.round(nice / metersPerPx);

  if (nice >= 1000) {
    label = `${(nice / 1000).toFixed(nice >= 10000 ? 0 : 1)} km`;
  } else {
    label = `${Math.round(nice)} m`;
  }

  document.getElementById('lo-scale-bar').style.width  = `${niceWidth}px`;
  document.getElementById('lo-scale-label').textContent = label;
}

/**
 * Round a number down to the nearest "nice" value (1, 2, 5, 10, 20, 50, …)
 * @param {number} value
 * @returns {number}
 */
function niceNumber(value) {
  const exp  = Math.floor(Math.log10(value));
  const frac = value / Math.pow(10, exp);
  let nice;
  if      (frac < 1.5) nice = 1;
  else if (frac < 3.5) nice = 2;
  else if (frac < 7.5) nice = 5;
  else                 nice = 10;
  return nice * Math.pow(10, exp);
}

/* ============================================================
   11. UTILITIES
   ============================================================ */

/**
 * Compute the bounding box of any GeoJSON object.
 * Returns [[minLng, minLat], [maxLng, maxLat]] or null.
 * @param {object} geojson
 * @returns {[[number,number],[number,number]]|null}
 */
function computeBounds(geojson) {
  let minLng =  Infinity, minLat =  Infinity;
  let maxLng = -Infinity, maxLat = -Infinity;

  function processCoord(coord) {
    if (coord[0] < minLng) minLng = coord[0];
    if (coord[0] > maxLng) maxLng = coord[0];
    if (coord[1] < minLat) minLat = coord[1];
    if (coord[1] > maxLat) maxLat = coord[1];
  }

  function walkGeom(geom) {
    if (!geom) return;
    if (geom.type === 'Point') {
      processCoord(geom.coordinates);
    } else if (geom.type === 'MultiPoint' || geom.type === 'LineString') {
      geom.coordinates.forEach(processCoord);
    } else if (geom.type === 'MultiLineString' || geom.type === 'Polygon') {
      geom.coordinates.forEach(ring => ring.forEach(processCoord));
    } else if (geom.type === 'MultiPolygon') {
      geom.coordinates.forEach(poly => poly.forEach(ring => ring.forEach(processCoord)));
    } else if (geom.type === 'GeometryCollection') {
      geom.geometries.forEach(walkGeom);
    }
  }

  if (geojson.type === 'FeatureCollection') {
    geojson.features.forEach(f => walkGeom(f.geometry));
  } else if (geojson.type === 'Feature') {
    walkGeom(geojson.geometry);
  } else {
    walkGeom(geojson);
  }

  if (!isFinite(minLng)) return null;
  return [[minLng, minLat], [maxLng, maxLat]];
}

/**
 * Escape HTML special characters to prevent XSS in popup content.
 * @param {string} str
 * @returns {string}
 */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&#x27;');
}

/**
 * Display a brief dismissible notification at the bottom of the screen.
 * @param {string} message
 * @param {'info'|'success'|'warning'|'error'} [type='info']
 */
function showToast(message, type = 'info') {
  // Ensure the toast container exists
  let container = document.getElementById('toast-container');
  if (!container) {
    container = document.createElement('div');
    container.id = 'toast-container';
    document.body.appendChild(container);
  }

  const toast = document.createElement('div');
  toast.className = `toast ${type}`;
  toast.textContent = message;
  container.appendChild(toast);

  // Auto-remove after 3.5 s
  setTimeout(() => {
    toast.style.opacity = '0';
    toast.style.transition = 'opacity 0.3s';
    setTimeout(() => toast.remove(), 320);
  }, 3500);
}

/* ============================================================
   ARCGIS ONLINE INTEGRATION
   ============================================================ */

/**
 * Search ArcGIS Online for public Feature Services, Map Services,
 * and Image Services (IMS) matching the user's query.
 *
 * Uses the ArcGIS Portal sharing REST search API (no API key required
 * for public content).
 *
 * @param {string} query
 */
async function searchArcGISOnline(query) {
  const trimmed = query.trim();
  const resultsEl = document.getElementById('arcgis-results');

  if (!trimmed) {
    resultsEl.innerHTML = '';
    return;
  }

  resultsEl.innerHTML = '<p class="arcgis-msg">Searching…</p>';

  try {
    const params = new URLSearchParams({
      q: trimmed,
      num: '8',
      f: 'json',
      access: 'public',
      type: 'Feature Service,Map Service,Image Service'
    });

    const res = await fetch(
      `https://www.arcgis.com/sharing/rest/search?${params}`
    );
    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const data = await res.json();
    const results = (data.results || []).filter(item => item.url);

    if (results.length === 0) {
      resultsEl.innerHTML = '<p class="arcgis-msg">No results found.</p>';
      return;
    }

    renderArcGISResults(results);
  } catch (err) {
    resultsEl.innerHTML =
      `<p class="arcgis-msg error">Search failed: ${escapeHtml(err.message)}</p>`;
    console.error('[SounnyMap] ArcGIS search error:', err);
  }
}

/**
 * Render ArcGIS Online search result cards into the sidebar panel.
 * @param {Array} results  – items from the ArcGIS sharing search API
 */
function renderArcGISResults(results) {
  const container = document.getElementById('arcgis-results');
  container.innerHTML = '';

  results.forEach(item => {
    const typeLabel =
      item.type === 'Feature Service' ? 'Feature' :
      item.type === 'Image Service'   ? 'Image'   : 'Map';

    const div = document.createElement('div');
    div.className = 'arcgis-result-item';
    div.innerHTML = `
      <div class="arcgis-result-info">
        <div class="arcgis-result-title"
             title="${escapeHtml(item.title || item.name || 'Untitled')}"
        >${escapeHtml(item.title || item.name || 'Untitled')}</div>
        <div class="arcgis-result-meta">
          ${escapeHtml(item.owner || '')}
          <span class="arcgis-type-badge">${typeLabel}</span>
        </div>
      </div>
      <button class="arcgis-add-btn" type="button" title="Add to map">Add</button>
    `;

    div.querySelector('.arcgis-add-btn').addEventListener('click', async (e) => {
      const btn = e.currentTarget;
      btn.disabled = true;
      btn.textContent = '…';
      await addArcGISService(item);
      btn.textContent = '✓';
    });

    container.appendChild(div);
  });
}

/**
 * Add an ArcGIS Online service to the map.
 *
 * Feature Services are queried and loaded as GeoJSON vector layers.
 * Map Services and Image Services (IMS) are added as raster tile layers
 * using the ArcGIS REST tile endpoint pattern: /tile/{z}/{y}/{x}.
 *
 * @param {object} item  – ArcGIS portal item from the search results
 */
async function addArcGISService(item) {
  const serviceUrl = (item.url || '').replace(/\/$/, '');
  const rawName = item.title || item.name || 'ArcGIS Layer';
  const name = escapeHtml(rawName);

  if (!serviceUrl) {
    showToast('No service URL available for this item.', 'warning');
    return;
  }

  if (item.type === 'Feature Service') {
    // Fetch the first layer as GeoJSON
    const queryUrl =
      `${serviceUrl}/0/query?` +
      `where=1%3D1&outFields=*&f=geojson&resultRecordCount=1000&outSR=4326`;

    try {
      const res = await fetch(queryUrl);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const geojson = await res.json();
      if (!geojson.type) throw new Error('Invalid GeoJSON response');
      loadGeoJSON(rawName, geojson);
      const count = geojson.features ? geojson.features.length : 0;
      if (count >= 1000) {
        showToast(`"${name}" loaded (first 1000 features – dataset may be larger)`, 'warning');
      } else {
        showToast(`Added "${name}"`, 'success');
      }
    } catch (err) {
      showToast(`Could not load "${name}": ${err.message}`, 'error');
      console.error('[SounnyMap] ArcGIS FeatureService error:', err);
    }
  } else {
    // Map Service or Image Service → raster tile layer
    // ArcGIS REST tile URL: /tile/{z}/{row}/{col} == /tile/{z}/{y}/{x}
    const tilesUrl = `${serviceUrl}/tile/{z}/{y}/{x}`;
    const layerId  = `arcgis-${rawName.replace(/\s+/g, '-').toLowerCase()}-${++layerCounter}`;

    try {
      addRasterLayer(layerId, tilesUrl, {
        attribution: `${rawName} (ArcGIS Online)`,
        opacity: 0.85
      });
      showToast(`Added "${name}" as tile layer`, 'success');
    } catch (err) {
      showToast(`Could not add "${name}": ${err.message}`, 'error');
      console.error('[SounnyMap] ArcGIS MapService error:', err);
    }
  }
}

/* ============================================================
   EARTH OBSERVATION / AGENT INTEGRATION STUBS
   ============================================================ */

/**
 * Add a raster tile layer (WMS, TMS, or XYZ) to the map.
 * Call this function from your EO data pipeline or agent tool.
 *
 * Examples:
 *   // NASA GIBS MODIS True Colour
 *   addRasterLayer('modis', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/' +
 *     'MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-01-01/GoogleMapsCompatible/{z}/{y}/{x}.jpg');
 *
 *   // Custom tile server
 *   addRasterLayer('eo-product', 'https://my-tile-server.example.com/tiles/{z}/{x}/{y}.png');
 *
 * @param {string} id        - Unique layer ID
 * @param {string} tilesUrl  - XYZ tile URL template
 * @param {object} [opts]    - Optional overrides: { attribution, minzoom, maxzoom, opacity }
 */
function addRasterLayer(id, tilesUrl, opts = {}) {
  const sourceId = `${id}-raster-src`;

  if (map.getSource(sourceId)) {
    console.warn(`[SounnyMap] Source "${sourceId}" already exists. Remove it first.`);
    return;
  }

  map.addSource(sourceId, {
    type: 'raster',
    tiles: [tilesUrl],
    tileSize: opts.tileSize || 256,
    attribution: opts.attribution || ''
  });

  map.addLayer({
    id: `${id}-raster-layer`,
    type: 'raster',
    source: sourceId,
    minzoom: opts.minzoom ?? 0,
    maxzoom: opts.maxzoom ?? 22,
    paint: {
      'raster-opacity': opts.opacity ?? 0.85
    }
  });
}

// Expose key functions globally so external scripts can call them
window.SounnyMap = {
  loadGeoJSON,
  updateLayerData,
  addRasterLayer,
  map  // expose the raw MapLibre instance for advanced use
};

/* ============================================================
   12. EVENT LISTENERS
   ============================================================ */

/** Sidebar toggle (hamburger button in header) */
document.getElementById('sidebar-toggle').addEventListener('click', () => {
  const sidebar = document.getElementById('sidebar');
  const overlay = document.getElementById('sidebar-overlay');
  const isNowCollapsed = sidebar.classList.toggle('collapsed');
  overlay.classList.toggle('active', !isNowCollapsed);
});

/** Mobile sidebar overlay – tap to close */
document.getElementById('sidebar-overlay').addEventListener('click', () => {
  document.getElementById('sidebar').classList.add('collapsed');
  document.getElementById('sidebar-overlay').classList.remove('active');
});

/** Basemap switcher buttons */
document.querySelectorAll('.basemap-btn').forEach(btn => {
  btn.addEventListener('click', () => switchBasemap(btn.dataset.basemap));
});

/** File browse button → open file picker */
document.getElementById('upload-btn').addEventListener('click', (e) => {
  e.stopPropagation();
  document.getElementById('geojson-input').click();
});

/** File input change (files chosen via dialog) */
document.getElementById('geojson-input').addEventListener('change', (e) => {
  loadFiles(e.target.files);
  e.target.value = ''; // Reset so the same file can be re-uploaded
});

/** Click on drop area also opens file picker */
document.getElementById('upload-drop-area').addEventListener('click', () => {
  document.getElementById('geojson-input').click();
});

/** Keyboard accessibility for drop area */
document.getElementById('upload-drop-area').addEventListener('keydown', (e) => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault();
    document.getElementById('geojson-input').click();
  }
});

/** Drag-and-drop: dragover */
document.getElementById('upload-drop-area').addEventListener('dragover', (e) => {
  e.preventDefault();
  e.currentTarget.classList.add('dragover');
});

/** Drag-and-drop: dragleave */
document.getElementById('upload-drop-area').addEventListener('dragleave', (e) => {
  e.currentTarget.classList.remove('dragover');
});

/** Drag-and-drop: drop */
document.getElementById('upload-drop-area').addEventListener('drop', (e) => {
  e.preventDefault();
  e.currentTarget.classList.remove('dragover');
  loadFiles(e.dataTransfer.files);
});

/** Map area also accepts drag-and-drop */
document.getElementById('map').addEventListener('dragover', (e) => e.preventDefault());
document.getElementById('map').addEventListener('drop', (e) => {
  e.preventDefault();
  if (e.dataTransfer.files.length) loadFiles(e.dataTransfer.files);
});

/** Open layout mode */
document.getElementById('layout-mode-btn').addEventListener('click', () => {
  if (layoutModeActive) {
    deactivateLayoutMode();
  } else {
    activateLayoutMode();
  }
});

/** Close layout mode */
document.getElementById('layout-close-btn').addEventListener('click', deactivateLayoutMode);

/** Live-sync layout overlay as inputs change */
['lp-title-input', 'lp-sources-input'].forEach(id => {
  document.getElementById(id).addEventListener('input', () => {
    if (layoutModeActive) syncLayoutOverlay();
  });
});

['lp-show-title', 'lp-show-legend', 'lp-show-north', 'lp-show-scale', 'lp-show-sources'].forEach(id => {
  document.getElementById(id).addEventListener('change', () => {
    if (layoutModeActive) syncLayoutOverlay();
  });
});

/** Export PDF button */
document.getElementById('export-pdf-btn').addEventListener('click', exportToPDF);

/** ArcGIS Online search – button click */
document.getElementById('arcgis-search-btn').addEventListener('click', () => {
  searchArcGISOnline(document.getElementById('arcgis-search-input').value);
});

/** ArcGIS Online search – Enter key */
document.getElementById('arcgis-search-input').addEventListener('keydown', (e) => {
  if (e.key === 'Enter') searchArcGISOnline(e.target.value);
});

/* ============================================================
   13. BOOTSTRAP
   ============================================================ */

/** Wait for the map to finish loading before showing the ready toast */
map.on('load', () => {
  showToast('Map ready. Load GeoJSON data or switch basemaps to begin.', 'success');
  updateLayerCount();
});

/** On mobile viewports, start with the sidebar collapsed so the map is immediately visible */
if (window.matchMedia('(max-width: 640px)').matches) {
  document.getElementById('sidebar').classList.add('collapsed');
}
